apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: renebod/fastapi:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          # resources:
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"      

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: LoadBalancer
  selector:
    app: fastapi
  ports:
    - port: 8080
      targetPort: 8000
